# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 07:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20170703_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe', to='blogs.Blog', verbose_name='Блог'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe', to=settings.AUTH_USER_MODEL, verbose_name='Подписанный пользователь'),
        ),
    ]
